//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parade.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Person
    {
        public long id { get; set; }
        [DisplayName("First Name")]
        public string First_Name { get; set; }
        [DisplayName("Middle Name")]
        public string Middle_Name { get; set; }
        [DisplayName("Last Name")]
        public string Last_Name { get; set; }
        public string Taluko { get; set; }
        public string District { get; set; }
        [DisplayName("Date of Birth")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> Date_of_Birth { get; set; }
        [DisplayName("Medical History")]
        [DataType(DataType.MultilineText)]
        public string Medical_History { get; set; }
    }
}
